
# install dependencies needed to run the docker lxc engine (http://www.docker.io/)
# Basically a reworking of docker's Vagrentfile[1] into an ansible-playbook
# [1] https://github.com/dotcloud/docker/blob/master/Vagrantfile

- name: Install {{ item }} # defined in group_vars/hosting.yml
  apt: package={{ item }} update_cache=yes state=present
  with_items: linux_kernel
  sudo: yes
  notify:
  - restart server

- name: Pre-repo add dependencies
  apt: pkg={{ item }} state=latest
  with_items: docker_deps
  sudo: yes

- name: Install apt-transport-https 
  apt: package=apt-transport-https update_cache=yes state=present
  sudo: yes

- name: Add docker repository key
  apt_key: url=https://get.docker.io/gpg state=present
  sudo: yes
 
- name: Add docker repository
  apt_repository: repo="{{ docker_apt }}" state=present
  sudo: yes

- name: Install docker
  apt: pkg=lxc-docker state=latest update_cache=yes
  sudo: yes
  notify:
  - restart server


